[devshell]
name = "Briar2nix"

startup.main.text = "cd nix"

[android]
toolsVersion = "26.1.1"
platformToolsVersion = "31.0.3"
buildToolsVersions = [ "28.0.3", "30.0.3" ]
platformVersions = [ "30" ]
abiVersions = [ "armeabi-v7a", "arm64-v8a" ]
